name: GitHub Actions Demo
on: [push]
         
jobs:
  pmd-code-scan:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
          
      - name: Run tests
        run: |
          # install opensource COBOL
          sudo apt-get install -y gcc build-essential make bison flex libgmp3-dev libncurses5-dev libncursesw5-dev
          sudo apt-get install -y autoconf diffutils
          sudo apt-get install -y gzip 
          pwd
          cd 
          mkdir opt
          chmod -R 777 opt/
          cd opt

          curl -L -o opensource-cobol-1.5.2J.tar.gz https://github.com/opensourcecobol/opensource-cobol/archive/v1.5.2J.tar.gz
          ls
          tar zxvf opensource-cobol-1.5.2J.tar.gz
          ls
          cd opensource-cobol-1.5.2J/vbisam/
          ./configure --prefix=/usr/
          sudo make install
          cd ../
          ./configure --prefix=/usr/ --with-vbisam
          sudo make install
          cd /
          cd opt
          rm -rf opensource-cobol-1.5.2J opensource-cobol-1.5.2J.tar.gz

          # install OCESQL
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y postgresql-client-12
          sudo apt-get install -y postgresql-contrib
          sudo apt-get install -y libpq-dev
          sudo apt-get -y install postgresql
          
          curl -L -o Open-COBOL-ESQL-1.2.tar.gz https://github.com/opensourcecobol/Open-COBOL-ESQL/archive/v1.2.tar.gz
          ls
          tar zxvf Open-COBOL-ESQL-1.2.tar.gz
          ls
          cd Open-COBOL-ESQL-1.2/
          ./configure --prefix=/usr/
          sudo make install
          

